name: Tools Release

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/**'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Generate Tag
        id: tag
        run: |
          TAG="tools-v$(date +'%Y%m%d%H%M%S')"
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Build (Mac/ARM64)
        run: GOOS=darwin GOARCH=arm64 go build -o ../dist/fruits-cli-darwin-arm64
      
      - name: Build (Windows/AMD64)
        run: GOOS=windows GOARCH=amd64 go build -o ../dist/fruits-cli-windows-amd64.exe

      - name: Build (Linux/AMD64)
        run: GOOS=linux GOARCH=amd64 go build -o ../dist/fruits-cli-linux-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          files: |
            dist/fruits-cli-darwin-arm64
            dist/fruits-cli-windows-amd64.exe
            dist/fruits-cli-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
